# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: {{ .Values.name }}-{{ include "hotel-reservation.fullname" . }}
#   labels:
#     hotel-reservation/service: {{ .Values.name }}--{{ include "hotel-reservation.fullname" . }}
# data:
#   # Add your configuration data here
#   tempo-config: |-
#     {{ .Files.Get "configs/tempo.yaml" | nindent 4 }}

{{include "hotel-reservation.templates.baseConfigMap" .}}
