name: telemetry-loki
replicas: 1
ports:
  - port: 3100
    targetPort: 3100

container:
  image: grafana/loki
  imageVersion: latest
  name: hotel-reserv-telemetry-loki
  args: ["--pattern-ingester.enabled=true", "-config.file=/etc/loki/loki.yaml"]
  ports:
    - containerPort: 3100

configMaps:
  - name: loki.yaml
    mountPath: /etc/loki/loki.yaml
    value: loki-config
