/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.chords.travel.choreographies;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
