services:
  benchmark:
    image: accompanist-benchmark
    environment:
      BENCHMARK: "chain-benchmark"
      ORCHESTRATOR: "toxiproxy:5000"
      CHOREOGRAPHY: "toxiproxy:6000"
      TOXIPROXY: "toxiproxy:8474"

  orchestrator:
    image: accompanist-benchmark
    environment:
      BENCHMARK: "chain-orchestrator"
      PORT: "5000"
      FIRST: "toxiproxy:9001"
      SECOND: "toxiproxy:9002"
      THIRD: "toxiproxy:9003"
      FOURTH: "toxiproxy:9004"
      FIFTH: "toxiproxy:9005"

  sidecar-start:
    image: accompanist-benchmark
    environment:
      BENCHMARK: "chain-sidecar-start"
      PORT: "6000"
      NEXT_SIDECAR: "toxiproxy:8001"
  sidecar-a:
    image: accompanist-benchmark
    environment:
      BENCHMARK: "chain-sidecar-a"
      SERVICE: "toxiproxy:9001"
      NEXT_SIDECAR: "toxiproxy:8002"
      START: "toxiproxy:8000"
  sidecar-b:
    image: accompanist-benchmark
    environment:
      BENCHMARK: "chain-sidecar-b"
      SERVICE: "toxiproxy:9002"
      NEXT_SIDECAR: "toxiproxy:8003"
  sidecar-c:
    image: accompanist-benchmark
    environment:
      BENCHMARK: "chain-sidecar-c"
      SERVICE: "toxiproxy:9003"
      NEXT_SIDECAR: "toxiproxy:8004"
      START: "toxiproxy:8000"
  sidecar-d:
    image: accompanist-benchmark
    environment:
      BENCHMARK: "chain-sidecar-d"
      SERVICE: "toxiproxy:9004"
      NEXT_SIDECAR: "toxiproxy:8005"
  sidecar-e:
    image: accompanist-benchmark
    environment:
      BENCHMARK: "chain-sidecar-e"
      SERVICE: "toxiproxy:9005"
      NEXT_SIDECAR: "toxiproxy:8000"

  service-a:
    image: accompanist-benchmark
    environment:
      BENCHMARK: "greeter"
      PORT: "5430"
  service-b:
    image: accompanist-benchmark
    environment:
      BENCHMARK: "greeter"
      PORT: "5430"
  service-c:
    image: accompanist-benchmark
    environment:
      BENCHMARK: "greeter"
      PORT: "5430"
  service-d:
    image: accompanist-benchmark
    environment:
      BENCHMARK: "greeter"
      PORT: "5430"
  service-e:
    image: accompanist-benchmark
    environment:
      BENCHMARK: "greeter"
      PORT: "5430"

  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.12.0
    command: [ "-host=0.0.0.0", "-config=/toxiproxy.json" ]
    volumes:
      - "./toxiproxy.json:/toxiproxy.json"
