services:
  first:
    image: accompanist-benchmark
    environment:
      BENCHMARK: "chain-a"
      SIDECAR: "first-sidecar"
      NEXT_ADDRESS: "second"
  second:
    image: accompanist-benchmark
    environment:
      BENCHMARK: "chain-b"
      SIDECAR: "second-sidecar"
      NEXT_ADDRESS: "third"
  third:
    image: accompanist-benchmark
    environment:
      BENCHMARK: "chain-c"
      SIDECAR: "third-sidecar"
      NEXT_ADDRESS: "first"

  first-sidecar:
    image: accompanist-benchmark
    environment:
      BENCHMARK: "greeter"
  second-sidecar:
    image: accompanist-benchmark
    environment:
      BENCHMARK: "greeter"
  third-sidecar:
    image: accompanist-benchmark
    environment:
      BENCHMARK: "greeter"

  toxiproxy:
    image: ghcr.io/shopify/toxiproxy:2.12.0
    volumes:
      - "./toxiproxy.json:/config/toxiproxy.json"