apiVersion: v1
kind: Service
metadata:
  name: loadgenerator
  labels:
    app: loadgenerator
spec:
  ports:
    - port: 8089
      protocol: TCP
  clusterIP: None
  selector:
    app: loadgenerator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  labels:
    app: loadgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
        - name: loadgenerator
          image: loadgenerator
          env:
            - name: FRONTEND_ADDR
              value: "warehouse:5000"
            - name: USERS
              value: "10"
