apiVersion: v1
kind: ServiceAccount
metadata:
  name: fault-tolerance-loadgenerator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fault-tolerance-loadgenerator
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  resourceNames:
  - payment
  - temporal-worker-payment
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments/scale
  resourceNames:
  - payment
  - temporal-worker-payment
  verbs:
  - get
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fault-tolerance-loadgenerator
subjects:
- kind: ServiceAccount
  name: fault-tolerance-loadgenerator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fault-tolerance-loadgenerator
---
apiVersion: v1
kind: Service
metadata:
  name: loadgenerator
  labels:
    app: loadgenerator
spec:
  ports:
  - port: 8089
    protocol: TCP
  clusterIP: None
  selector:
    app: loadgenerator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  labels:
    app: loadgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      serviceAccountName: fault-tolerance-loadgenerator
      containers:
      - name: loadgenerator
        image: loadgenerator
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: BENCHMARK_SYSTEM
          value: accompanist
        volumeMounts:
        - name: runs
          mountPath: /runs
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: '2'
            memory: 2Gi
        readinessProbe:
          httpGet:
            path: /
            port: 8089
          periodSeconds: 2
      terminationGracePeriodSeconds: 600
      volumes:
      - name: runs
        persistentVolumeClaim:
          claimName: benchmark-runs
  strategy:
    type: Recreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benchmark-runs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
