/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.2/userguide/building_java_projects.html in the Gradle documentation.
 */

group = "org.choral-lang"
version = "0.1.0"

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish`

    id("com.google.protobuf") version "0.9.4"
    id("com.vanniktech.maven.publish") version "0.36.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()

    pom {
        name.set("Accompanist")
        description.set("A fault-tolerant runtime for Choral choreographies.")
        inceptionYear.set("2025")
        url.set("https://github.com/chords-project/choral-accompanist")
        licenses {
            license {
                name.set("GNU Lesser General Public License v3.0")
                url.set("https://www.gnu.org/licenses/lgpl-3.0.html")
                distribution.set("https://www.gnu.org/licenses/lgpl-3.0.html")
            }
        }
        developers {
            developer {
                id.set("viktorstrate")
                name.set("Viktor Strate Kløvedal")
                url.set("https://qpqp.dk/")
            }
        }
        scm {
            url.set("https://github.com/chords-project/choral-accompanist")
            connection.set("scm:git:git://github.com/chords-project/choral-accompanist.git")
            developerConnection.set("scm:git:ssh://git@github.com/chords-project/choral-accompanist.git")
        }
    }
}

var choralVersion = "0.1.12"
var grpcVersion = "1.68.1"
var otelVersion = "1.47.0"

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // ## Choral ##
    api("org.choral-lang:choral:${choralVersion}")
    api("org.choral-lang:runtime:${choralVersion}")

    // ## OpenTelemetry SDK ##

    // using the bom ensures that all of your opentelemetry dependency versions are aligned
    api(platform("io.opentelemetry:opentelemetry-bom:${otelVersion}"))

    api("io.opentelemetry:opentelemetry-api")
    api("io.opentelemetry:opentelemetry-sdk")
    api("io.opentelemetry:opentelemetry-exporter-otlp")
    api("io.opentelemetry:opentelemetry-exporter-logging-otlp")
    api("io.opentelemetry:opentelemetry-exporter-logging")
    api("io.opentelemetry.instrumentation:opentelemetry-grpc-1.6:2.13.3-alpha")

    // ## gRPC ##
    runtimeOnly("io.grpc:grpc-netty-shaded:${grpcVersion}")
    implementation("io.grpc:grpc-protobuf:${grpcVersion}")
    implementation("io.grpc:grpc-stub:${grpcVersion}")
    implementation("io.grpc:grpc-opentelemetry:${grpcVersion}")
    implementation("io.grpc:grpc-services:${grpcVersion}")
    compileOnly("org.apache.tomcat:annotations-api:6.0.53")

    implementation("org.zeromq:jeromq:0.6.0")
    api("com.rabbitmq:amqp-client:5.25.0")

    implementation("com.zaxxer:HikariCP:6.3.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(23)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

// Compile protobuf code
protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.25.5"
    }
    plugins {
        create("grpc") {
            artifact = "io.grpc:protoc-gen-grpc-java:1.68.1"
        }
    }
    generateProtoTasks {
        all().forEach { task ->
            task.plugins {
                create("grpc") {}
            }
        }
    }
}
