apiVersion: 1

datasources:
  - name: Loki
    type: loki
    # access: proxy
    uid: loki
    url: http://loki:3100
    # jsonData:
    #   derivedFields:
    #     - datasourceUid: tempo
    #       matcherRegex: "^.*?traceI[d|D]=(\\w+).*$"
    #       name: traceId
    #       url: '$${__value.raw}'
    jsonData:
      derivedFields:
        - name: "traceid"
          matcherType: "label"
          matcherRegex: "traceid"
          url: "$${__value.raw}"
          datasourceUid: "tempo"
          urlDisplayLabel: "Trace: $${__value.raw}"

  - name: Tempo
    type: tempo
    # access: proxy
    uid: tempo
    url: http://tempo:3200
    jsonData:
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: "loki"
      serviceMap:
        datasourceUid: 'Mimir'
      # tracesToLogs:
      #   datasourceUid: loki
      #   filterByTraceID: false
      #   spanEndTimeShift: "500ms"
      #   spanStartTimeShift: "-500ms"
      tracesToLogsV2:
        customQuery: true
        datasourceUid: "loki"
        query: '{$${__tags}} | traceid = "$${__trace.traceId}"'
        tags:
          - key: "service.name"
            value: "service_name"
      tracesToProfiles:
        customQuery: false
        datasourceUid: "pyroscope"
        profileTypeId: "process_cpu:cpu:nanoseconds:cpu:nanoseconds"
        tags:
          - key: "service.name"
            value: "service_name"

  - name: Mimir
    type: prometheus
    # access: proxy
    uid: mimir
    url: http://mimir:9009/prometheus
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: traceID
      httpMethod: POST
      timeInterval: "2s"

  - name: Pyroscope
    type: phlare
    # access: proxy
    uid: pyroscope
    url: http://pyroscope:4040
    jsonData:
      backendType: pyroscope

  - name: "mongodb-geo"
    type: "haohanyang-mongodb-datasource"
    # access: proxy
    jsonData:
      host: mongodb-geo
      port: 27017
      database: geo-db
      authType: auth-none

  - name: "mongodb-profile"
    type: "haohanyang-mongodb-datasource"
    # access: proxy
    jsonData:
      host: mongodb-profile
      port: 27017
      database: profile-db
      authType: auth-none

  - name: "mongodb-review"
    type: "haohanyang-mongodb-datasource"
    # access: proxy
    jsonData:
      host: mongodb-review
      port: 27017
      database: review-db
      authType: auth-none

  - name: "mongodb-rate"
    type: "haohanyang-mongodb-datasource"
    # access: proxy
    jsonData:
      host: mongodb-rate
      port: 27017
      database: rate-db
      authType: auth-none

  - name: "mongodb-recommendation"
    type: "haohanyang-mongodb-datasource"
    # access: proxy
    jsonData:
      host: mongodb-recommendation
      port: 27017
      database: recommendation-db
      authType: auth-none

  - name: "mongodb-reservation"
    type: "haohanyang-mongodb-datasource"
    # access: proxy
    jsonData:
      host: mongodb-reservation
      port: 27017
      database: reservation-db
      authType: auth-none

  - name: "mongodb-user"
    type: "haohanyang-mongodb-datasource"
    # access: proxy
    jsonData:
      host: mongodb-user
      port: 27017
      database: user-db
      authType: auth-none

  - name: "mongodb-flights"
    type: "haohanyang-mongodb-datasource"
    # access: proxy
    jsonData:
      host: mongodb-flights
      port: 27017
      database: flights-db
      authType: auth-none