name: telemetry-alloy
replicas: 1
ports:
  - port: 12347
    targetPort: 12345
  - port: 12348
    targetPort: 12348
  - port: 6832
    targetPort: 6832
  - port: 55679
    targetPort: 55679
  - port: 4317
    targetPort: 4317
  - port: 4318
    targetPort: 4318
  - port: 9999
    targetPort: 9999

container:
  image: grafana/alloy
  imageVersion: latest
  name: hotel-reserv-telemetry-alloy
  args:
    - "run"
    - "--server.http.listen-addr=0.0.0.0:12345"
    - "--stability.level=public-preview"
    - "/etc/alloy/config.alloy"
  ports:
    - containerPort: 12347
    - containerPort: 12348
    - containerPort: 6832
    - containerPort: 55679
    - containerPort: 4317
    - containerPort: 4318
    - containerPort: 9999

configMaps:
  - name: config.alloy
    mountPath: /etc/alloy/config.alloy
    value: config-alloy
  - name: endpoints.json
    mountPath: /etc/alloy/endpoints.json
    value: endpoints-json
