name: geo

ports:
  - port: 8083
    targetPort: 8083

container:
  command: geo
  image: hotel-reservation
  name: hotel-reserv-geo
  ports:
    - containerPort: 8083

sidecar:
  image: travel-sidecar-geo

configMaps:
  - name: service-config.json
    mountPath: /workspace/config.json
    value: service-config
