name: telemetry-grafana
replicas: 1
ports:
  - port: 3000
    targetPort: 3000

container:
  image: deathstarbench/grafana
  imageVersion: latest
  name: hotel-reserv-telemetry-grafana
  ports:
    - containerPort: 3000
