{{- define "hotel-reservation.templates.service-config.json" }}
{
    "consulAddress": "consul-{{ include "hotel-reservation.service-url" . }}:8500",
    "otlpAddress": "telemetry-alloy-{{ include "hotel-reservation.service-url" . }}:4317",
    "FrontendPort": "5000",
    "GeoPort": "8081",
    "GeoMongoAddress": "mongodb-geo-{{ include "hotel-reservation.service-url" . }}:27018",
    "ProfilePort": "8081",
    "ProfileMongoAddress": "mongodb-profile-{{ include "hotel-reservation.service-url" . }}:27019",
    "ProfileMemcAddress": {{ include "hotel-reservation.generateMemcAddr" (list . .Values.global.memcached.HACount "memcached-profile" 11213)}},
    "RatePort": "8081",
    "RateMongoAddress": "mongodb-rate-{{ include "hotel-reservation.service-url" . }}:27020",
    "RateMemcAddress": {{ include "hotel-reservation.generateMemcAddr" (list . .Values.global.memcached.HACount "memcached-rate" 11212)}},
    "RecommendPort": "8081",
    "RecommendMongoAddress": "mongodb-recommendation-{{ include "hotel-reservation.service-url" . }}:27021",
    "ReservePort": "8081",
    "ReserveMongoAddress": "mongodb-reservation-{{ include "hotel-reservation.service-url" . }}:27022",
    "ReserveMemcAddress": {{ include "hotel-reservation.generateMemcAddr" (list . .Values.global.memcached.HACount "memcached-reserve" 11214)}},
    "SearchPort": "8081",
    "UserPort": "8081",
    "UserMongoAddress": "mongodb-user-{{ include "hotel-reservation.service-url" . }}:27023",
    "ReviewPort": "8081",
    "ReviewMongoAddress": "mongodb-review-{{ include "hotel-reservation.service-url" . }}:27024",
    "ReviewMemcAddress": {{ include "hotel-reservation.generateMemcAddr" (list . .Values.global.memcached.HACount "memcached-review" 11215)}},
    "AttractionsPort": "8081",
    "AttractionsMongoAddress": "mongodb-attractions-{{ include "hotel-reservation.service-url" . }}:27025",
    "FlightsPort": "8081",
    "FlightsMongoAddress": "mongodb-flights-{{ include "hotel-reservation.service-url" . }}:27026",
    "FlightsGrpcAddress": "a05e4e3477931431f84a40e19a636a21-220131330.eu-west-3.elb.amazonaws.com:8081"
}
{{- end }}
