name: flights

ports:
  - port: 8090
    targetPort: 8090

container:
  command: flights
  image: hotel-reservation
  name: hotel-reserv-flights
  ports:
    - containerPort: 8090

sidecar:
  image: travel-sidecar-flight

configMaps:
  - name: service-config.json
    mountPath: /workspace/config.json
    value: service-config
