apiVersion: v1
kind: Service
metadata:
  name: warehouse
  labels:
    app: warehouse
spec:
  ports:
    - name: "choral"
      port: 4003
      protocol: TCP
    - name: "web-endpoint"
      port: 5000
      protocol: TCP
  clusterIP: None
  selector:
    app: warehouse
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse
  labels:
    app: warehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouse
  template:
    metadata:
      labels:
        app: warehouse
    spec:
      initContainers:
        - name: check-warehouse-db-ready
          image: postgres
          command: [
            'sh', '-c',
            'until pg_isready -h db-warehouse -p 5432; 
                    do echo waiting for database; sleep 2; done;'
          ]
      containers:
        - name: warehouse-sidecar
          image: warehouse
          env:
            - name: RUN
              value: 'sidecar'
            - name: WAREHOUSE
              value: warehouse:4001
            - name: PAYMENT
              value: payment:4002
            - name: LOYALTY
              value: loyalty:4003
            - name: POSTGRES_URL
              value: "postgresql://db-warehouse:5432/warehouse"
            - name: LISTEN_PORT
              value: "5000"
        - name: warehouse-service
          image: warehouse
          env:
            - name: RUN
              value: 'service'
            - name: POSTGRES_URL
              value: "postgresql://db-warehouse:5432/warehouse"
            - name: LISTEN_PORT
              value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: db-warehouse
  labels:
    app: db-warehouse
spec:
  ports:
    - port: 5432
      protocol: TCP
  clusterIP: None
  selector:
    app: db-warehouse
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-warehouse
  labels:
    app: db-warehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-warehouse
  template:
    metadata:
      labels:
        app: db-warehouse
    spec:
      containers:
        - name: db-warehouse
          image: postgres
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: warehouse
