apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - benchmark-runtime-settings
  - warehouse/deployment.yaml
  - warehouse/database
  - loyalty/deployment.yaml
  - payment/deployment.yaml
  - loadgenerator/deployment.yaml
  - observability/deployment.yaml
  - monitor/deployment.yaml

configMapGenerator:
  - name: grafana-accompanist-provisioning
    files:
      - accompanist.yaml=observability/grafana/provisioning/accompanist.yaml
  - name: grafana-accompanist-dashboards
    files:
      - accompanist-overview.json=observability/grafana/dashboards/accompanist-overview.json

patches:
  - target:
      kind: Deployment
      name: loadgenerator
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - configMapRef:
              name: accompanist-runtime-settings
