apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: warehouse
build:
  artifacts:
    - image: loyalty
      context: loyalty
      jib:
        project: loyalty
    - image: payment
      context: payment
      jib:
        project: payment
    - image: warehouse-temporal
      context: temporal
      jib:
        project: temporal
    - image: warehouse
      context: warehouse
      jib:
        project: warehouse
    - image: loadgenerator
      context: loadgenerator
manifests:
  rawYaml:
    - temporal/deployment.yaml
    - temporal/temporal.yaml
    - warehouse/deployment.yaml
    - loyalty/deployment.yaml
    - payment/deployment.yaml
    - loadgenerator/deployment.yaml
portForward:
  - resourceType: service
    resourceName: warehouse
    port: 5000
  - resourceType: service
    resourceName: loadgenerator
    port: 8089
  - resourceType: service
    resourceName: temporal-warehouse-endpoint
    port: 5001
  - resourceType: service
    resourceName: temporal-ui
    port: 8080