apiVersion: v1
kind: Service
metadata:
  name: loyalty
  labels:
    app: loyalty
spec:
  ports:
    - port: 4003
      protocol: TCP
  clusterIP: None
  selector:
    app: loyalty
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty
  labels:
    app: loyalty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty
  template:
    metadata:
      labels:
        app: loyalty
    spec:
      affinity: # Deploy on same node as db service
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - db-loyalty
      initContainers:
        - name: check-loyalty-db-ready
          image: postgres
          command: [
            'sh', '-c',
            'until pg_isready -h db-loyalty -p 5432; 
                    do echo waiting for database; sleep 2; done;'
          ]
      containers:
        - name: loyalty-sidecar
          image: loyalty
          env:
            - name: RUN
              value: 'sidecar'
            - name: WAREHOUSE
              value: warehouse:4001
            - name: PAYMENT
              value: payment:4002
            - name: LOYALTY
              value: loyalty:4003
            - name: POSTGRES_URL
              value: "postgresql://db-loyalty:5432/loyalty"
        - name: loyalty-service
          image: loyalty
          env:
            - name: RUN
              value: 'service'
            - name: POSTGRES_URL
              value: "postgresql://db-loyalty:5432/loyalty"
---
apiVersion: v1
kind: Service
metadata:
  name: db-loyalty
  labels:
    app: db-loyalty
spec:
  ports:
    - port: 5432
      protocol: TCP
  clusterIP: None
  selector:
    app: db-loyalty
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-loyalty
  labels:
    app: db-loyalty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-loyalty
  template:
    metadata:
      labels:
        app: db-loyalty
    spec:
      containers:
        - name: db-loyalty
          image: postgres
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: loyalty
