apiVersion: v1
kind: Service
metadata:
  name: loyalty
  labels:
    app: loyalty
spec:
  ports:
  - port: 4003
    protocol: TCP
  clusterIP: None
  selector:
    app: loyalty
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty
  labels:
    app: loyalty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty
  template:
    metadata:
      labels:
        app: loyalty
    spec:
      containers:
      - name: loyalty
        image: loyalty
