name: frontend

ports:
  - port: 5000
    targetPort: 5000

container:
  command: frontend
  image: hotel-reservation
  name: hotel-reserv-frontend
  ports:
    - containerPort: 5000

sidecar:
  image: travel-sidecar-client
  ports:
    - 8945

configMaps:
  - name: service-config.json
    mountPath: /workspace/config.json
    value: service-config
