name: review

ports:
  - port: 8088
    targetPort: 8088

container:
  command: review
  image: hotel-reservation
  dockerRegistry: europe-west1-docker.pkg.dev/chords-microservice-444208/webshop-repo
  name: hotel-reserv-review
  ports:
    - containerPort: 8088

configMaps:
  - name: service-config.json
    mountPath: /workspace/config.json
    value: service-config
