apiVersion: v1
kind: Service
metadata:
  name: db-warehouse
  labels:
    app: db-warehouse
spec:
  ports:
  - port: 5432
    protocol: TCP
  clusterIP: None
  selector:
    app: db-warehouse
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-warehouse
  labels:
    app: db-warehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-warehouse
  template:
    metadata:
      labels:
        app: db-warehouse
    spec:
      containers:
      - name: db-warehouse
        image: postgres:17.6
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: warehouse
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: '2'
            memory: 2Gi
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - pg_isready -U postgres
          periodSeconds: 2
