apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: accompanist-runtime-settings
    envs:
      - accompanist-runtime-settings.env
  - name: temporal-runtime-settings
    envs:
      - temporal-runtime-settings.env
  - name: warehouse-dns-settings
    files:
      - warehouse-dns.security
