{{- $values := .Values -}}
{{- range $chain := .Values.chain }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $chain.name }}-{{ include "accompanist-benchmark.fullname" $ }}
  labels:
    {{- include "accompanist-benchmark.labels" $ | nindent 4 }}
spec:
  type: {{ $values.service.type }}
  ports:
    - port: {{ $values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "accompanist-benchmark.selectorLabels" $ | nindent 4 }}
{{- end }}
