name: search

ports:
  - port: 8082
    targetPort: 8082

container:
  command: search
  image: hotel-reservation
  dockerRegistry: europe-west1-docker.pkg.dev/chords-microservice-444208/webshop-repo
  name: hotel-reserv-search
  ports:
    - containerPort: 8082

configMaps:
  - name: service-config.json
    mountPath: /workspace/config.json
    value: service-config
